"""FollowUpCallAgent — uses ElevenLabs Conversational AI to phone the council.

Takes a CivicIssue that has been through the escalation agent (has a phone
script in escalation_history), configures an ElevenLabs voice agent with that
script, and initiates an outbound call to the council.

Flow:
    1. Extract the phone script from issue.escalation_history
    2. Build a system prompt for the ElevenLabs agent from the script
    3. Create a ConvAI agent (or reuse ELEVENLABS_AGENT_ID from config)
    4. Place the outbound call to the council phone number
    5. Return the conversation result on the issue
"""

from __future__ import annotations

import logging
from typing import Optional

from src.config import ELEVENLABS_AGENT_ID, ELEVENLABS_PHONE_NUMBER_ID
from src.integrations.elevenlabs import ElevenLabsClient, ConversationResult
from src.models.base import CivicIssue

logger = logging.getLogger(__name__)

# Council switchboard numbers — a production system would pull these from a
# maintained database or the council's website.
COUNCIL_PHONE_NUMBERS: dict[str, str] = {
    "City of London Corporation": "+442076064030",
    "London Borough of Barking and Dagenham": "+442082154430",
    "London Borough of Barnet": "+442083592000",
    "London Borough of Bexley": "+442083037777",
    "London Borough of Brent": "+442089379400",
    "London Borough of Bromley": "+442084644600",
    "London Borough of Camden": "+442079742000",
    "London Borough of Croydon": "+442087261000",
    "London Borough of Ealing": "+442088255000",
    "London Borough of Enfield": "+442083791000",
    "London Borough of Greenwich": "+442088546000",
    "London Borough of Hackney": "+442083565000",
    "London Borough of Hammersmith and Fulham": "+442087489500",
    "London Borough of Haringey": "+442084891000",
    "London Borough of Harrow": "+442088631234",
    "London Borough of Havering": "+441708434343",
    "London Borough of Hillingdon": "+441895250111",
    "London Borough of Hounslow": "+442085832000",
    "London Borough of Islington": "+442075272000",
    "Royal Borough of Kensington and Chelsea": "+442073615000",
    "Royal Borough of Kingston upon Thames": "+442085471000",
    "London Borough of Lambeth": "+442079261000",
    "London Borough of Lewisham": "+442083146000",
    "London Borough of Merton": "+442085454454",
    "London Borough of Newham": "+442084302000",
    "London Borough of Redbridge": "+442085540000",
    "London Borough of Richmond upon Thames": "+442088919000",
    "London Borough of Southwark": "+442075255000",
    "London Borough of Sutton": "+442087706000",
    "London Borough of Tower Hamlets": "+442073641447",
    "London Borough of Waltham Forest": "+442084964000",
    "London Borough of Wandsworth": "+442088717000",
    "City of Westminster": "+442076412000",
}


AGENT_SYSTEM_PROMPT = """\
You are a polite, professional AI caller following up on behalf of a London \
resident about an unresolved civic complaint. You are calling the council to \
check on the status of the report and request a resolution timeline.

RULES:
- Be courteous and patient. You are speaking with a council officer.
- State the reference number clearly and spell it out if asked.
- Ask for: (1) current status, (2) expected resolution date, (3) the officer's \
name and direct contact.
- If they cannot help, ask to be transferred to the relevant department.
- If put on hold, wait patiently.
- If you reach voicemail, leave a clear message with the reference number and \
a callback number.
- Keep the call under 5 minutes.
- At the end, thank the officer and confirm you will follow up in writing.

ISSUE DETAILS:
{issue_context}

PHONE SCRIPT TO FOLLOW:
{phone_script}
"""


class FollowUpCallAgent:
    """Places a follow-up phone call to the council via ElevenLabs Conversational AI."""

    def __init__(
        self,
        elevenlabs: ElevenLabsClient | None = None,
        agent_id: str = ELEVENLABS_AGENT_ID,
        phone_number_id: str = ELEVENLABS_PHONE_NUMBER_ID,
    ) -> None:
        self.elevenlabs = elevenlabs or ElevenLabsClient()
        self.agent_id = agent_id
        self.phone_number_id = phone_number_id

    def process(self, issue: CivicIssue) -> CivicIssue:
        """Place a follow-up call for an escalated issue.

        Expects issue.escalation_history to contain a follow_up entry with
        a phone_script field (generated by EscalationAgent).
        """
        phone_script = self._extract_phone_script(issue)
        if not phone_script:
            logger.warning("No phone script found in escalation history for %s", issue.id)
            return issue

        council_number = self._get_council_number(issue.council)

        agent_id = self.agent_id or self._create_agent(issue, phone_script)

        first_message = (
            f"Hello, my name is the London Civic Agent automated service. "
            f"I am calling on behalf of a resident about civic issue "
            f"reference {issue.id}, which was reported to your "
            f"{issue.department} department {issue.days_open} days ago."
        )

        result = self.elevenlabs.make_outbound_call(
            agent_id=agent_id,
            agent_phone_number_id=self.phone_number_id,
            to_number=council_number,
            first_message=first_message,
        )

        self._record_call(issue, result, council_number)
        return issue

    def get_call_status(self, conversation_id: str) -> ConversationResult:
        """Poll for the status of a previously initiated call."""
        return self.elevenlabs.get_conversation(conversation_id)

    def _extract_phone_script(self, issue: CivicIssue) -> str:
        for entry in issue.escalation_history:
            if entry.get("stage") == "follow_up" and entry.get("phone_script"):
                return entry["phone_script"]
        return ""

    def _get_council_number(self, council_name: str) -> str:
        number = COUNCIL_PHONE_NUMBERS.get(council_name, "")
        if not number:
            for key, val in COUNCIL_PHONE_NUMBERS.items():
                if council_name.lower() in key.lower() or key.lower() in council_name.lower():
                    return val
        return number or "+442079461000"  # generic London council line fallback

    def _create_agent(self, issue: CivicIssue, phone_script: str) -> str:
        """Create a one-off ElevenLabs Conversational AI agent for this call."""
        issue_context = (
            f"Reference: {issue.id}\n"
            f"Issue: {issue.title}\n"
            f"Category: {issue.category}\n"
            f"Council: {issue.council}\n"
            f"Department: {issue.department}\n"
            f"Days open: {issue.days_open}\n"
            f"Severity: {issue.severity_score}/10\n"
            f"Location: {issue.address or issue.borough}"
        )

        system_prompt = AGENT_SYSTEM_PROMPT.format(
            issue_context=issue_context,
            phone_script=phone_script,
        )

        first_message = (
            f"Hello, I am calling about civic issue reference {issue.id}."
        )

        agent = self.elevenlabs.create_agent(
            name=f"Council Follow-up — {issue.id}",
            system_prompt=system_prompt,
            first_message=first_message,
        )
        logger.info("Created follow-up agent %s for issue %s", agent.agent_id, issue.id)
        return agent.agent_id

    def _record_call(
        self,
        issue: CivicIssue,
        result: ConversationResult,
        council_number: str,
    ) -> None:
        """Append call details to the issue's escalation history."""
        for entry in issue.escalation_history:
            if entry.get("stage") == "follow_up":
                entry["call_initiated"] = True
                entry["conversation_id"] = result.conversation_id
                entry["call_status"] = result.status
                entry["council_number_called"] = council_number
                break
