"""SubmissionAgent — generate a formal report from a processed CivicIssue."""

from __future__ import annotations

import logging
from datetime import datetime

from src.models.base import CivicIssue, LLMProvider
from src.models.mock import MockProvider
from src.prompts import load_prompt

logger = logging.getLogger(__name__)


class SubmissionAgent:
    """Generates formal submission text suitable for FixMyStreet or council portals."""

    def __init__(self, llm: LLMProvider) -> None:
        self.llm = llm
        self._prompt_tpl = load_prompt("submission_generate")

    def process(self, issue: CivicIssue) -> CivicIssue:
        """Populate issue.submission_text with a formal report."""
        issue.submission_text = self._generate_report(issue)
        issue.status = "submitted"
        return issue

    def _generate_report(self, issue: CivicIssue) -> str:
        """Build a formal report -- uses templates in mock mode, LLM otherwise."""
        # In mock mode, always use the structured template
        if isinstance(self.llm, MockProvider):
            return self._template_report(issue)

        prompt = self._build_prompt(issue)
        system = (
            "You are writing a formal civic complaint report to a London borough "
            "council. Be clear, factual, and actionable. Include all relevant "
            "details. Keep it under 300 words."
        )
        raw = self.llm.generate(prompt, system=system)
        logger.debug("Raw submission generation response (%d chars): %r", len(raw), raw[:200])
        return raw if raw.strip() else self._template_report(issue)

    def _build_prompt(self, issue: CivicIssue) -> str:
        coords = ""
        if issue.latitude and issue.longitude:
            coords = f"{issue.latitude:.6f}, {issue.longitude:.6f}"
        photo_line = ""
        if issue.photos:
            photo_line = f"{len(issue.photos)} photo(s) attached."

        return self._prompt_tpl.format(
            council=issue.council,
            category=issue.category,
            subcategory=issue.subcategory or "N/A",
            address=issue.address or "See coordinates",
            coordinates=coords or "N/A",
            borough=issue.borough,
            severity_score=issue.severity_score,
            severity_justification=issue.severity_justification,
            description=issue.description,
            photo_line=photo_line,
        )

    def _template_report(self, issue: CivicIssue) -> str:
        """Structured template for mock mode."""
        now = datetime.now().strftime("%d %B %Y at %H:%M")
        photo_line = (
            f"{len(issue.photos)} photograph(s) have been attached to this report."
            if issue.photos
            else ""
        )
        location_line = issue.address or "See map coordinates below"
        coords_line = ""
        if issue.latitude and issue.longitude:
            coords_line = f"Map reference: {issue.latitude:.6f}, {issue.longitude:.6f}\n"

        lines = [
            "CIVIC ISSUE REPORT",
            "==================",
            f"Date: {now}",
            f"Reference: {issue.id}",
            f"Category: {issue.category}",
            f"Subcategory: {issue.subcategory or 'N/A'}",
            f"Severity: {issue.severity_score}/10",
            "",
            "LOCATION",
            "--------",
            f"Address: {location_line}",
            coords_line.rstrip(),
            f"Borough: {issue.borough}",
            "",
            "ROUTING",
            "-------",
            f"Council: {issue.council}",
            f"Department: {issue.department}",
            "",
            "DESCRIPTION",
            "-----------",
            issue.description,
        ]
        if photo_line:
            lines.append(photo_line)
        lines += [
            "",
            "SEVERITY ASSESSMENT",
            "-------------------",
            f"Score: {issue.severity_score}/10",
            f"Justification: {issue.severity_justification}",
            "",
            "---",
            "This report was generated by the London Civic Agent system.",
            f"Submitted to: {issue.council} — {issue.department}",
        ]
        # Filter out empty strings from coords_line when no coordinates
        return "\n".join(line for line in lines if line is not None)
